
package dom.cafam.newhotel.integracionerp_subsidio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultarInfoAfil_NewHotel_Out", targetNamespace = "http://newhotel.cafam.dom/integracionERP_Subsidio")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class,
    dom.cafam.newhotel.integracionerp_subsisio.ObjectFactory.class
})
public interface ConsultarInfoAfilNewHotelOut {

    /**
     * 
     * @param consultarInfoAfilNewHotelRequest
     * @return
     *     returns dom.cafam.newhotel.integracionerp_subsidio.InfoAfilNewHotel
     */

    @WebMethod(operationName = "ConsultarInfoAfil_NewHotel_Sync", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ConsultarInfoAfil_NewHotelResponse", targetNamespace = "http://newhotel.cafam.dom/integracionERP_Subsisio", partName = "ConsultarInfoAfil_NewHotelResponse")
    public InfoAfilNewHotel consultarInfoAfilNewHotelSync(
            @WebParam(name = "ConsultarInfoAfil_NewHotelRequest", targetNamespace = "http://newhotel.cafam.dom/integracionERP_Subsisio", partName = "ConsultarInfoAfil_NewHotelRequest")
                    InfoAfilNewHotelRequest consultarInfoAfilNewHotelRequest);


}

