
package dom.cafam.newhotel.integracionerp_subsidio;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XI_9ef3c41e5d9d30f893ca355afc87c682_Service", targetNamespace = "http://newhotel.cafam.dom/integracionERP_Subsidio", wsdlLocation = "file:/Users/gasotelo/NetBeansProjects/TestSmartObjects/src/conf/xml-resources/web-services/CafamAfiliadios/wsdl/BSP_NEWHOTEL_ConsultarInfoAfil_NewHotel_Out.wsdl")
public class XI9Ef3C41E5D9D30F893Ca355Afc87C682Service
    extends Service
{

    private final static URL XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_WSDL_LOCATION;
    private final static WebServiceException XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_EXCEPTION;
    private final static QName XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_QNAME = new QName("http://newhotel.cafam.dom/integracionERP_Subsidio", "XI_9ef3c41e5d9d30f893ca355afc87c682_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:./servicio_CAFAM.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_WSDL_LOCATION = url;
        XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_EXCEPTION = e;
    }

    public XI9Ef3C41E5D9D30F893Ca355Afc87C682Service() {
        super(__getWsdlLocation(), XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_QNAME);
    }

    public XI9Ef3C41E5D9D30F893Ca355Afc87C682Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_QNAME, features);
    }

    public XI9Ef3C41E5D9D30F893Ca355Afc87C682Service(URL wsdlLocation) {
        super(wsdlLocation, XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_QNAME);
    }

    public XI9Ef3C41E5D9D30F893Ca355Afc87C682Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_QNAME, features);
    }

    public XI9Ef3C41E5D9D30F893Ca355Afc87C682Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XI9Ef3C41E5D9D30F893Ca355Afc87C682Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultarInfoAfilNewHotelOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public ConsultarInfoAfilNewHotelOut getHTTPPort() {
        return super.getPort(new QName("http://newhotel.cafam.dom/integracionERP_Subsidio", "HTTP_Port"), ConsultarInfoAfilNewHotelOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarInfoAfilNewHotelOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public ConsultarInfoAfilNewHotelOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://newhotel.cafam.dom/integracionERP_Subsidio", "HTTP_Port"), ConsultarInfoAfilNewHotelOut.class, features);
    }

    /**
     * 
     * @return
     *     returns ConsultarInfoAfilNewHotelOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public ConsultarInfoAfilNewHotelOut getHTTPSPort() {
        return super.getPort(new QName("http://newhotel.cafam.dom/integracionERP_Subsidio", "HTTPS_Port"), ConsultarInfoAfilNewHotelOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarInfoAfilNewHotelOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public ConsultarInfoAfilNewHotelOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://newhotel.cafam.dom/integracionERP_Subsidio", "HTTPS_Port"), ConsultarInfoAfilNewHotelOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_EXCEPTION!= null) {
            throw XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_EXCEPTION;
        }
        return XI9EF3C41E5D9D30F893CA355AFC87C682SERVICE_WSDL_LOCATION;
    }

}
